# See rdkit/Chem/__init__.pyi for why these stubs exist.
from typing import Any

from rdkit.Chem import Mol

class MolDrawOptions:
    clearBackground: bool
    bondLineWidth: float
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...

class MolDraw2DSVG:
    def __init__(self, width: int, height: int) -> None: ...
    def drawOptions(self) -> MolDrawOptions: ...
    def DrawMolecule(self, mol: Mol) -> None: ...
    def FinishDrawing(self) -> None: ...
    def GetDrawingText(self) -> str: ...
