"""record when a drug's literature was searched

Revision ID: 0f0f806f8c5a
Revises: da70483fb545
Create Date: 2026-07-17 15:33:04.662839

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0f0f806f8c5a'
down_revision: str | None = 'da70483fb545'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug', sa.Column('literature_fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drug', 'literature_fetched_at')
    # ### end Alembic commands ###
