"""record when a drug's literature was searched

Revision ID: 0f0f806f8c5a
Revises: da70483fb545
Create Date: 2026-07-17 15:33:04.662839

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0f0f806f8c5a'
down_revision: str | None = 'da70483fb545'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug', sa.Column('literature_fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Backfill, and this is not tidiness -- without it the column ships a lie.
    #
    # The new column means "NULL = nobody has searched PubMed for this drug". Adding
    # it unfilled makes that statement false for every drug that already HAS
    # abstracts: they were searched, the rows are right there, and the column says
    # nobody looked. Measured on the dev database before this was written:
    # osimertinib had 10 linked abstracts and `was_searched()` returned False, so the
    # retriever skipped the vector search entirely and the model was handed the
    # sentence "PubMed has never been searched for this drug -- nobody has looked".
    #
    # That is this project's founding bug, arriving for the third time in one branch,
    # this time inside the fix for the second time. The lesson keeps being the same:
    # the collapse is never in the design, it is in some path nobody walked. Nothing
    # in the schema or the test suite was wrong -- only the data was, and only on a
    # database that already had rows, which is every database except a test's.
    #
    # A drug with links was searched. When is the only question, and each abstract
    # carries the retrieved_at of the fetch that stored it, so the latest one is the
    # last time we looked. Drugs with no links stay NULL, which is correct: nobody
    # has looked at them.
    op.execute(
        """
        UPDATE drug
           SET literature_fetched_at = latest.fetched_at
          FROM (
                SELECT da.drug_chembl_id, MAX(a.retrieved_at) AS fetched_at
                  FROM drug_abstract da
                  JOIN abstract a ON a.pmid = da.pmid
                 GROUP BY da.drug_chembl_id
               ) AS latest
         WHERE drug.chembl_id = latest.drug_chembl_id
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drug', 'literature_fetched_at')
    # ### end Alembic commands ###
