"""track when a drug was last enriched

Revision ID: 7693de4f2523
Revises: 90aee02e0978
Create Date: 2026-07-16 22:31:04.884338

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7693de4f2523'
down_revision: str | None = '90aee02e0978'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column('drug', sa.Column('last_enriched_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_drug_last_enriched_at'), 'drug', ['last_enriched_at'], unique=False)

    # Backfill from the evidence. NULL means "never analyzed", and every drug that
    # already has facts plainly has been -- leaving them NULL would tell the lazy
    # enricher to re-fetch every one of them against a source that 500s a third of
    # the time. The newest fact's retrieved_at is when we actually looked, which is
    # more honest than stamping now().
    op.execute(
        """
        UPDATE drug d
           SET last_enriched_at = f.latest
          FROM (
                SELECT drug_chembl_id, MAX(retrieved_at) AS latest
                  FROM fact
                 GROUP BY drug_chembl_id
               ) f
         WHERE f.drug_chembl_id = d.chembl_id
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drug_last_enriched_at'), table_name='drug')
    op.drop_column('drug', 'last_enriched_at')
    # ### end Alembic commands ###
