"""drug catalog and fact provenance

Revision ID: 90aee02e0978
Revises: 
Create Date: 2026-07-16 16:03:22.197770

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '90aee02e0978'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug',
    sa.Column('chembl_id', sa.String(length=20), nullable=False),
    sa.Column('pref_name', sa.String(length=512), nullable=True),
    sa.Column('smiles', sa.String(), nullable=True),
    sa.Column('mw', sa.Float(), nullable=True),
    sa.Column('alogp', sa.Float(), nullable=True),
    sa.Column('hbd', sa.Integer(), nullable=True),
    sa.Column('hba', sa.Integer(), nullable=True),
    sa.Column('psa', sa.Float(), nullable=True),
    sa.Column('ro5_violations', sa.Integer(), nullable=True),
    sa.Column('drug_type', sa.String(length=128), nullable=True),
    sa.Column('max_phase', sa.Integer(), nullable=True),
    sa.Column('primary_target', sa.String(length=64), nullable=True),
    sa.Column('primary_indication', sa.String(length=512), nullable=True),
    sa.Column('maturity', sa.Enum('full', 'partial', 'index_only', name='data_maturity'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chembl_id', name=op.f('pk_drug'))
    )
    op.create_index(op.f('ix_drug_drug_type'), 'drug', ['drug_type'], unique=False)
    op.create_index(op.f('ix_drug_maturity'), 'drug', ['maturity'], unique=False)
    op.create_index(op.f('ix_drug_max_phase'), 'drug', ['max_phase'], unique=False)
    op.create_index(op.f('ix_drug_pref_name'), 'drug', ['pref_name'], unique=False)
    op.create_index(op.f('ix_drug_primary_target'), 'drug', ['primary_target'], unique=False)
    op.create_index('ix_drug_target_phase', 'drug', ['primary_target', 'max_phase'], unique=False)
    op.create_table('fact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drug_chembl_id', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('ok', 'empty', 'source_failed', name='fact_status'), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.CheckConstraint("status <> 'ok' OR value IS NOT NULL", name=op.f('ck_fact_ok_has_value')),
    sa.CheckConstraint("status <> 'source_failed' OR value IS NULL", name=op.f('ck_fact_failed_has_no_value')),
    sa.ForeignKeyConstraint(['drug_chembl_id'], ['drug.chembl_id'], name=op.f('fk_fact_drug_chembl_id_drug'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact')),
    sa.UniqueConstraint('drug_chembl_id', 'key', 'source', name='uq_fact_drug_key_source')
    )
    op.create_index('ix_fact_drug', 'fact', ['drug_chembl_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fact_drug', table_name='fact')
    op.drop_table('fact')
    op.drop_index('ix_drug_target_phase', table_name='drug')
    op.drop_index(op.f('ix_drug_primary_target'), table_name='drug')
    op.drop_index(op.f('ix_drug_pref_name'), table_name='drug')
    op.drop_index(op.f('ix_drug_max_phase'), table_name='drug')
    op.drop_index(op.f('ix_drug_maturity'), table_name='drug')
    op.drop_index(op.f('ix_drug_drug_type'), table_name='drug')
    op.drop_table('drug')
    # ### end Alembic commands ###
