"""abstracts with embeddings for retrieval

Revision ID: da70483fb545
Revises: 7693de4f2523
Create Date: 2026-07-17 09:17:59.217808

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# Autogenerate emitted `pgvector.sqlalchemy.vector.VECTOR(dim=384)` below without
# importing pgvector -- a NameError on the first run, in a migration, which is the
# worst place to find one.
import pgvector.sqlalchemy


revision: str = 'da70483fb545'
down_revision: str | None = '7693de4f2523'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Alembic's autogenerate does not see extensions, so it happily wrote a table
    # using the `vector` type without ever creating it. This has to come first, and
    # it has to be hand-written -- a re-autogenerate will drop it again.
    #
    # IF NOT EXISTS, and no matching DROP in downgrade(): the compose image ships
    # pgvector, so this may already be installed by someone other than us, and
    # removing an extension we did not add is not a downgrade of this migration --
    # it is damage to whatever else in the database was relying on it.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abstract',
    sa.Column('pmid', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('journal', sa.String(length=512), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(text IS NULL) = (embedding IS NULL)', name=op.f('ck_abstract_embedding_iff_text')),
    sa.PrimaryKeyConstraint('pmid', name=op.f('pk_abstract'))
    )
    op.create_index('ix_abstract_embedding', 'abstract', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('drug_abstract',
    sa.Column('drug_chembl_id', sa.String(length=20), nullable=False),
    sa.Column('pmid', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drug_chembl_id'], ['drug.chembl_id'], name=op.f('fk_drug_abstract_drug_chembl_id_drug'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pmid'], ['abstract.pmid'], name=op.f('fk_drug_abstract_pmid_abstract'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drug_chembl_id', 'pmid', name=op.f('pk_drug_abstract'))
    )
    op.create_index('ix_drug_abstract_drug', 'drug_abstract', ['drug_chembl_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_drug_abstract_drug', table_name='drug_abstract')
    op.drop_table('drug_abstract')
    op.drop_index('ix_abstract_embedding', table_name='abstract', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('abstract')
    # ### end Alembic commands ###
