"""index primary_indication for overview sort

Revision ID: e325e959f222
Revises: 0f0f806f8c5a
Create Date: 2026-07-17 19:26:48.446987

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e325e959f222'
down_revision: str | None = '0f0f806f8c5a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_drug_primary_indication'), 'drug', ['primary_indication'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drug_primary_indication'), table_name='drug')
    # ### end Alembic commands ###
